version: "3.7"
services:
  api:
      image: node:18
      container_name: noah-api_api
      working_dir: /noah-api
      entrypoint: ["/bin/bash", "./scripts/startup.sh"]
      volumes:
          - ./:/noah-api
      depends_on:
          - db
      ports:
        - "8080:8080"
  db:
      image: postgres:14
      container_name: noah-api_db
      restart: always
      ports:
          - "5427:5432"
      environment:
          POSTGRES_USER: noah-api
          POSTGRES_PASSWORD: password
          POSTGRES_DB: noah-api-db
      volumes:
        - ./noah-api-db:/var/lib/postgresql/data